stages:
  - code-check
  - tests

# Cache tox envs between builds
cache:
  paths:
  - testing/.tox/

code-check:
  stage: code-check
  image: leapcode/soledad:latest
  script:
    - cd testing
    - tox -e code-check

tests:
  stage: tests
  image: leapcode/soledad:latest
  services:
    - couchdb
  script:
    - cd testing
    - tox -- --couch-url http://couchdb:5984
